### ISSUE TITLE
Sprungziel nicht Gefunden | Jump Target Not found

### ISSUE THREAD

**Issue by Fox2k11** [TheMMC/In-Place_Upgrade_Helper#12]
die deutsche version des script funktioniert nicht es kommt der fehler "Das Sprungziel mainmenu nicht gefunden" 

die englische Version hingegen  funktioniert! 

Siehe Screenshot 
--

The German version of the script doesn't work, the error "the jump target mainmenu not found" occurs!

the English version, however, works!

![screenshot](https://github.com/TheMMC/In-Place_Upgrade_Helper/assets/5962856/44bb060b-5346-4d6a-8b7f-83293f94614f)

**Comment by TheMMC** [comment]
Ich hab das gerade mit einer VM getestet, hier geht alles wunderbar.
Sowohl mit externen Installationsmedien als auch in das Medium selbst kopiert.
Kannst du das noch einmal testen und genau sagen, wie du das gemacht hast?
Wo liegen die Installationsdateien, wo liegt die Batch (haben die Verzeichnisse Sonderzeichen etc).
So einen Fehler habe ich bisher nur gesehen, wenn die Batch beim ausführen auf einmal nicht mehr da ist oder während der Ausführung geändert wird, z.B. indem man den USB-Stick mittendrin rauszieht oder mit dem Editor die Datei bearbeitet, während die Batch noch läuft.

**Comment by TheMMC** [comment]
Kannst du eventuell mal die Batch neu runterladen? Vielleicht ist die einfach durch irgendwas fehlerhaft geworden. Ich kann es wirklich nicht nachstellen, auch auf meiner physikalischen Maschine nicht. Besonders komisch ist, das der eigentliche Code für Deutsch und Englisch komplett identisch ist, es wurde nur der Text ausgetauscht.
Hast du sonst irgendwas laufen, was da reingrätschen könnte? Drittanbieter Antivirus oder so?

**Comment by TheMMC** [comment]
Der Zeichensatz wird nicht definiert, sowohl die Englische als auch die Deutsche laufen einfach mit dem Standard-Zeichensatz. Ich tippe da immernoch auf Eset. Magst du die Batch Datei hier mal anhängen, damit ich gucken kann ob die irgendwie verändert wurde? Eventuell blockt Eset auch den Zugriff auf die Batch, weil irgend ein Textbaustein irgendwas triggert. Vieles von dem, was da in der Batch steht, wird ja auch für Aktivierungstools und Ähnliches benutzt. Auch werden gerne Scripte, die zu viel in zu kurzer Zeit in der Registry rumfummeln, geblockt. Also mitten drin, wenn das Programm entscheidet "jetzt ist aber genug".
Ich habe das Ding jetzt hier noch einmal mit Win10, Win11 getestet, beides auf realen Maschinen als auch in einer VM. Alles OK, es muss also an irgendwas liegen, was bei dir nicht mehr dem Microsoft-Standard entspricht. Zu 90% sind das Tools wie Drittanbieter-Antivirus oder Provacy/Optimierungs-Tools, die restlichen 10% alles andere.

**Comment by TheMMC** [comment]
Hast du die Dateien irgendwie bearbeitet? Oder den Inhalt per Hand in eine Text-Datei kopiert? Die Zeilenumbrüche haben ein anderes Format.
Nichtsdestotrotz kann ich auf Biegen und Brechen den Fehler nicht rekonstruieren, auch andere User können das nicht. Irgendwas muss mit deinem Windows vergurkt sein, der Fehler liegt nicht in der Batch sondern woanders.

**Comment by TheMMC** [comment]
Habs hingekriegt, ich hab mich jetzt über eine Stunde mit der Github-Doku rumgeschlagen, um zu verstehen, wie und warum Github an Batch-Dateien rumfummelt. Und wie man das abschalten kann. Keiner meiner Tester oder ich sind auf die Idee gekommen, die Batch von Github neu runterzuladen, wenn man sie schon hat.
Ich war zwischendrin schon so verzweifelt, ich habe mir hier nebenbei eine Windows-Installation mit der Testversion von Eset fertig gemacht. Weil Github meint irgendwas ohne Nachfrage selbstständig zu verändern, ist mir jetzt ein Großteil des Nachmittages flöten gegangen.
Und sorry, falls ich heute einen etwas unfreundlicheren Ton hatte, du hast mich eben arg beim Growzelt aufbauen gestört ;)
Danke für den Bugreport, du bekommst ein Shoutout im Changelog.
