### ISSUE TITLE
Is it possible to do w11 iot enterprise 24h2 to w11 iot enterprise LTSC 24h2 while keeping apps and files? 

### ISSUE THREAD

**Issue by NoUserNameForYou** [TheMMC/In-Place_Upgrade_Helper#17]
Possible to do in place upgrade?

**Comment by TheMMC** [comment]
Yes, that's possible. But keep in mind that this upgrade will not remove the Microsoft Store, it will be migrated from the currently installed Windows. So you will have a LTSC with a working MS store, if you want a "pure" LTSC without Store you'll have to do a clean install.

**Comment by NoUserNameForYou** [comment]
Thank you for the answer, after your reply I went and downloaded the 24h2 iot ent ltsc but it's only letting me "keep files" and not "keep apps, settings and files" upgrade.

**Comment by TheMMC** [comment]
Just did a test and it worked:
![grafik](https://github.com/user-attachments/assets/96deec11-5336-4b4c-9d2b-7c0c111b7c57)
(I only had the german Windows version at hand)
